# Generated by Django 5.2.8 on 2025-12-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0002_rename_componey_product_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Componey',
            new_name='Company',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
    ]
