# Generated by Django 5.2.8 on 2025-12-01 07:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attributes', '0001_initial'),
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='Product rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_exciting', models.BooleanField(default=False, help_text='Attractive or trending product')),
                ('free_shipping', models.BooleanField(default=False)),
                ('has_gift', models.BooleanField(default=False, help_text='Includes gift with product')),
                ('is_budget_friendly', models.BooleanField(default=False, help_text='Cheap product')),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='attributes.age')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brands.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='attributes.color')),
                ('componey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='companies.componey')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='attributes.country')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='attributes.gender')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='attributes.season')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='attributes.tag')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
                'ordering': ['-created_at'],
            },
        ),
    ]
