# Generated by Django 5.2.8 on 2025-12-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='componey',
            new_name='company',
        ),
    ]
